//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommentsWebService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class comment
    {
        [DisplayName("Unique Comment Number")] //On the display it will depict as Comment Number
        public int commentID { get; set; }

        [DisplayName("Comment")]
        public string commentDescription { get; set; }
    }
}
